In [1]:
%pip install Sastrawi

Requirement already satisfied: Sastrawi in .\.venv\Lib\site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#1. Import library
import pandas as pd
import re
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

print(stemmer.stem("mengerjakan"))

kerja

In [16]:
import pandas as pd

#2. Load Dataset
data = pd.read_csv("dataset.csv")
text_column = "content_article"

# Cek apakah dataset berhasil dimuat
print(data.head())
print("Kolom teks yang digunakan:", text_column)

  date_publication media_source  \
0       2026-01-01       Kontan
1       2026-01-01       Kontan
2       2026-01-01       Kontan
3       2026-01-01       Kontan
4       2026-01-01       Kontan

                                       title_article  \
0  Harga Emas Antam Hari Ini (28/3) Naik Rp 27.00...
1  Kejagung Tetapkan Samin Tan Tersangka, Ini Kas...
2  Asing Net Sell Rp 20,38 Triliun, Cek Saham yan...
3                          Berburu Emas di Pagi Buta
4  Hampir Rampung, ESDM Restui RKAB Batubara 580 ...

                                     content_article  \
0  Reporter: Noverius Laoli | Editor: Noverius La...
1  Reporter: kompas.com | Editor: Noverius Laoli ...
2  Reporter: Noverius Laoli | Editor: Noverius La...
3                      Format Non-Text/Gagal Ekstrak
4  Reporter: Sabrina Rhamadanty | Editor: Ignatia...

                                         url_article sentiment_label  \
0  https://investasi.kontan.co.id/news/harga-emas...          NETRAL
1  https://nasional.kontan.co.id/news/kejagung-te...          NETRAL
2  https://investasi.kontan.co.id/news/asing-net-...          NETRAL
3  https://insight.kontan.co.id/news/berburu-emas...          NETRAL
4  https://industri.kontan.co.id/news/hampir-ramp...          NETRAL

   polarity_score  ai_confidence
0             0.0         0.9178
1             0.0         0.9755
2             0.0         0.9794
3             0.0         0.0000
4             0.0         0.9716
Kolom teks yang digunakan: content_article

In [ ]:
#3.Case Folding
def case_folding(text):
    return str(text).lower()

# Contoh
text = "Saya Belajar NLP"
print(case_folding(text))
# Output: saya belajar nlp

saya belajar nlp

In [ ]:
#4. Menghapus URL
def remove_url(text):
    return re.sub(r"http\S+|www\S+", "", text)

# Contoh
text = "Kunjungi https://example.com sekarang"
print(remove_url(text))
# Output: Kunjungi  sekarang

Kunjungi  sekarang

In [ ]:
#5. Menghapus Mention
def remove_mention(text):
    return re.sub(r"@\w+", "", text)

# Contoh
text = "@user1 produk ini bagus"
print(remove_mention(text))

 produk ini bagus

In [ ]:
#6. Menghapus hashtag
def remove_hashtag(text):
    return re.sub(r"#\w+", "", text)

In [ ]:
#7. Menghapus Angka
def remove_number(text):
    return re.sub(r"\d+", "", text)

In [ ]:
#8. Menghapus Punctuation
def remove_punctuation(text):
    return text.translate(
        str.maketrans("", "", string.punctuation)
    )

In [ ]:
#9. Membersihkan whitespace
def clean_whitespace(text):
    return re.sub(r"\s+", " ", text).strip()

In [19]:
#10. Fungsi Cleaning Lengkap
def clean_text(text):
    text = str(text)
    text  = text.lower()
    text = remove_url(text)
    text = remove_mention(text)
    text = remove_hashtag(text)
    text = remove_number(text)
    text = remove_punctuation(text)
    text = clean_whitespace(text)
    return text

#menerapkan ke dataset
data["clean_text"] = data[text_column].apply(clean_text)
data[[text_column, "clean_text"]].head()

,content_article,clean_text
0,reporter noverius laoli editor noverius laoli ...,reporter noverius laoli editor noverius laoli ...
1,reporter kompascom editor noverius laoli konta...,reporter kompascom editor noverius laoli konta...
2,reporter noverius laoli editor noverius laoli ...,reporter noverius laoli editor noverius laoli ...
3,format nontextgagal ekstrak,format nontextgagal ekstrak
4,reporter sabrina rhamadanty editor ignatia mar...,reporter sabrina rhamadanty editor ignatia mar...

In [20]:
#11. Stopword Removal
stop_words = set(stopwords.words("indonesian"))

def remove_stopwords(tokens):
    return [
        token for token in tokens
        if token not in stop_words
    ]

# Contoh
tokens = ["saya", "sedang", "belajar", "nlp", "yang", "menarik"]
print(remove_stopwords(tokens))

['belajar', 'nlp', 'menarik']

In [21]:
#12. Stemming dengan Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

# Contoh
text = "Mahasiswa sedang mempelajari pemrograman."
print(stemmer.stem(text))

mahasiswa sedang ajar pemrograman

In [26]:
#13. Pipeline Preprocessing Lengkap
def preprocessing_pipeline(text):
    # 1. Cleaning
    text = clean_text(text)

    # 2. Tokenization
    tokens = word_tokenize(text)

    # 3. Stopword removal
    tokens = remove_stopwords(tokens)

    # 4. Stemming
    tokens = stem_tokens(tokens)

    return tokens

# Menerapkan ke dataset
data["processed_tokens"] = data[text_column].apply(preprocessing_pipeline)

In [27]:
#14. Menggabungkan Token Kembali
data["processed_text"] = data["processed_tokens"].apply(
    lambda tokens: " ".join(tokens)
)

In [28]:
#15. Perbandingan Raw vs Processed
for i in range(5):
    print("RAW:")
    print(data.iloc[i][text_column])

    print("\nPROCESSED:")
    print(data.iloc[i]["processed_text"])

    print("=" * 80)

RAW:
reporter noverius laoli editor noverius laoli kontancoid jakarta harga emas batangan bersertifikat antam keluaran logam mulia pt aneka tambang tbk antm naik pada sabtu mengutip situs logam mulia harga pecahan satu gram emas antam berada di rp harga emas antam itu naik dibandingkan dengan harga pada jumat yang berada di level rp per gram sementara harga buyback emas antam berada di level rp per gram harga tersebut naik rp jika dibandingkan dengan harga buyback pada jumat yang juga ada di rp per gram berikut harga emas batangan antam dalam pecahan lainnya per sabtu dan belum termasuk pajak harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp logam mulia antam menjual emas dan perak batangan dalam beberapa ukuran berat misalnya gram gram dan gram biasanya harga per gram emas antam akan berbeda tergantung berat batangnya perbedaan ini terjadi karena ada biaya tambahan untuk pencetakan sehingga harga per gram emas antam batang kecil lebih mahal dari batang yang lebih besar harga yang ada di sini adalah harga per gram emas batang kilogram yang biasa dijadikan patokan pelaku bisnis emas

PROCESSED:
reporter noverius laoli editor noverius laoli kontancoid jakarta harga emas batang sertifikat antam keluar logam mulia pt aneka tambang tbk antm sabtu kutip situs logam mulia harga pecah gram emas antam rp harga emas antam banding harga jumat level rp gram harga buyback emas antam level rp gram harga rp banding harga buyback jumat rp gram harga emas batang antam pecah sabtu pajak harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp harga emas gram rp logam mulia antam jual emas perak batang ukur berat gram gram gram harga gram emas antam beda gantung berat batang beda biaya tambah cetak harga gram emas antam batang mahal batang harga harga gram emas batang kilogram jadi patok laku bisnis emas
================================================================================
RAW:
reporter kompascom editor noverius laoli kontancoid jakarta kejaksaan agung kejagung menetapkan samin tan st sebagai tersangka dalam kasus dugaan korupsi pengelolaan tambang batubara pt asmin koalindo tuhup akt di murung raya kalimantan tengah penetapan ini terkait aktivitas tambang yang diduga tetap berjalan meski izin sudah dicabut sejak kepala pusat penerangan hukum kejagung anang supriatna mengatakan penetapan tersangka dilakukan setelah penyidik mengantongi alat bukti yang cukup “tim penyidik telah menetapkan tersangka st” ujarnya sabtu dini hari direktur penyidikan jampidsus syarief sulaeman nahdi menjelaskan penyidikan dilakukan melalui pemeriksaan sejumlah saksi dan penggeledahan di berbagai wilayah hingga kini penggeledahan masih berlangsung terutama di kalimantan tengah dan kalimantan selatan setelah sebelumnya juga dilakukan di jawa barat dan dki jakarta dalam konstruksi perkara samin tan disebut sebagai beneficiary owner pt akt perusahaan ini sebelumnya beroperasi dengan skema perjanjian karya pengusahaan pertambangan batubara pkpb sebelum izinnya dicabut pada namun setelah pencabutan izin tersebut pt akt diduga tetap melakukan kegiatan penambangan dan penjualan batubara secara ilegal hingga aktivitas itu disebut dilakukan melalui perusahaan afiliasi dengan menggunakan dokumen perizinan yang tidak sah penyidik juga menduga praktik tersebut melibatkan kerja sama dengan oknum penyelenggara negara yang memiliki kewenangan dalam pengawasan pertambangan dugaan pelanggaran ini berpotensi menimbulkan kerugian keuangan negara danatau perekonomian negara meski begitu nilai kerugian negara masih dalam proses penghitungan oleh badan pengawasan keuangan dan pembangunan bpkp kejagung menegaskan penyidikan dilakukan secara profesional dan menjunjung asas praduga tidak bersalah atas perbuatannya tersangka dijerat dengan pasal dan pasal kuhp penyidik masih terus mendalami kasus ini untuk mengungkap kemungkinan keterlibatan pihak lain sumber

PROCESSED:
reporter kompascom editor noverius laoli kontancoid jakarta jaksa agung jagung tetap samin tan st sangka duga korupsi kelola tambang batubara pt asmin koalindo tuhup akt murung raya kalimantan tetap kait aktivitas tambang duga jalan izin cabut kepala pusat terang hukum jagung anang supriatna tetap sangka sidik kantong alat bukti  tim sidik tetap sangka st  sabtu direktur sidi jampidsus syarief sulaeman nahdi sidi periksa saksi geledah wilayah geledah kalimantan kalimantan selatan jawa barat dki jakarta konstruksi perkara samin tan beneficiary owner pt akt usaha operasi skema janji karya usaha tambang batubara pkpb izin cabut cabut izin pt akt duga giat tambang jual batubara ilegal aktivitas usaha afiliasi dokumen izin sah sidik duga praktik libat kerja oknum selenggara negara milik wenang awas tambang duga langgar potensi timbul rugi uang negara danatau ekonomi negara nilai rugi negara proses hitung badan awas uang bangun bpkp jagung sidi profesional junjung asas praduga salah buat sangka jerat pasal pasal kuhp sidik dalam ungkap libat sumber
================================================================================
RAW:
reporter noverius laoli editor noverius laoli kontancoid jakarta indeks harga saham gabungan ihsg kembali ditutup di zona merah pada akhir perdagangan jumat memperpanjang tren pelemahan yang sudah terjadi sejak hari sebelumnya tekanan jual terutama dari investor asing menjadi beban utama pergerakan pasar sepanjang pekan berdasarkan data bursa efek indonesia bei ihsg turun atau poin ke level sepanjang sesi indeks bergerak dalam rentang hingga dalam sepekan terakhir ihsg tercatat melemah pelemahan ini mencerminkan tekanan yang belum mereda di pasar saham domestik meski aktivitas perdagangan terbilang ramai tekanan jual tetap mendominasi volume transaksi mencapai miliar saham dengan nilai rp triliun ihsg kembali menipis hari ini maret © konten oleh kontan dari seluruh saham yang diperdagangkan sebanyak saham turun saham naik dan saham stagnan aksi jual investor asing menjadi sorotan utama pada perdagangan jumat asing mencatatkan jual bersih net sell sebesar rp triliun di seluruh pasar bahkan secara akumulatif dalam sepekan terakhir nilai net sell asing telah menembus rp triliun besarnya arus keluar dana asing ini menjadi faktor penekan utama ihsg sekaligus menandakan sentimen pasar yang masih cenderung berhatihati berikut saham net sell terbesar asing sepekan terakhir pt bank central asia tbk bbca rp triliun pt bank rakyat indonesia tbk bbri rp triliun pt bank negara indonesia tbk bbni rp miliar pt medco energi internasional tbk medc rp miliar pt bank mandiri tbk bmri rp miliar pt aneka tambang tbk antm rp miliar pt goto gojek tokopedia tbk goto rp miliar pt impack pratama industri tbk impc rp miliar pt amman mineral internasional tbk ammn rp miliar pt merdeka battery materials tbk mbma rp miliar

PROCESSED:
reporter noverius laoli editor noverius laoli kontancoid jakarta indeks harga saham gabung ihsg tutup zona merah dagang jumat panjang tren lemah tekan jual investor asing beban utama gera pasar pekan dasar data bursa efek indonesia bei ihsg turun poin level sesi indeks gerak rentang pek ihsg catat lemah lemah cermin tekan reda pasar saham domestik aktivitas dagang bilang ramai tekan jual dominasi volume transaksi capai miliar saham nilai rp triliun ihsg tip maret  konten kontan saham dagang saham turun saham saham stagnan aksi jual investor asing sorot utama dagang jumat asing catat jual bersih net sell rp triliun pasar akumulatif pek nilai net sell asing tembus rp triliun besar arus dana asing faktor tekan utama ihsg tanda sentimen pasar cenderung berhatihati saham net sell besar asing pek pt bank central asia tbk bbca rp triliun pt bank rakyat indonesia tbk bbri rp triliun pt bank negara indonesia tbk bbni rp miliar pt medco energi internasional tbk medc rp miliar pt bank mandiri tbk bmri rp miliar pt aneka tambang tbk antm rp miliar pt goto gojek tokopedia tbk goto rp miliar pt impack pratama industri tbk impc rp miliar pt amman mineral internasional tbk ammn rp miliar pt merdeka battery materials tbk mbma rp miliar
================================================================================
RAW:
format nontextgagal ekstrak

PROCESSED:
format nontextgagal ekstrak
================================================================================
RAW:
reporter sabrina rhamadanty editor ignatia maria sri sayekti kontancoid – jakarta kementerian esdm melalui direktorat jenderal mineral dan batubara ditjen minerba menyebut telah menerbitkan juta ton rencana kerja dan anggaran biaya rkab produksi batubara dan juta ton rkab produksi nikel jika dibandingkan target rkab batubara tahun ini adalah jutaan ton diikuti dengan nikel diangka juta ton adapun dengan angka ini direktur jenderal mineral dan batu bara dirjen minerba kementerian esdm tri winarno menyebut persetujaun rkab khususnya untuk batubara segera rampung “batubara hampir finish lah yang an lah tapi nikel ada di atas ” ungkap tri saat ditemui di kantor kementerian perekonomian jakarta jumat di sisi lain tri mengamini soal keputusan kementerian esdm yang akan menerapkan pajak ekspor pada produk turunan atau produk hilirisasi nikel diantaranya nickel pig iron npi dan mhp mixed hydroxide precipitate “ada beberapa produk turunan iya termasuk mhp” ungkap tri sebelumnya menteri bahlil bilang komoditas tambang menjadi salah satu sumber untuk mencari alternatifalternatif pendapatan negara melalui pengenaan pajak ekspor terhadap hasil hilirisasi saat ini yang dibidik adalah pengenaan pajak untuk ekspor produk nickel pig iron npi yang merupakan produk antara hasil pengolahan bijih nikel laterit kadar rendah dalam industri npi merupakan besi mentah pig iron yang difungsikan sebagai bahan baku utama dalam industri stainless steel baja tahan karat sebagai alternatif feronikel yang lebih murah “seperti npi npi produk daripada nikel lagi kita menghitung ini lagi kita menghitung ya sekali lagi saya lagi menghitung tentang formulasi daripada pengenaan pajak npinya” jelas bahlil

PROCESSED:
reporter sabrina rhamadanty editor ignatia maria sri sayekti kontancoid  jakarta menteri esdm direktorat jenderal mineral batubara ditjen minerba sebut terbit juta ton rencana kerja anggar biaya rkab produksi batubara juta ton rkab produksi nikel banding target rkab batubara juta ton ikut nikel angka juta ton angka direktur jenderal mineral batu bara dirjen minerba menteri esdm tri winarno sebut persetujaun rkab batubara rampung  batubara finish an nikel  tri temu kantor menteri ekonomi jakarta jumat sisi tri amin putus menteri esdm terap pajak ekspor produk turun produk hilir nikel nickel pig iron npi mhp mixed hydroxide precipitate  produk turun iya mhp  tri menteri bahlil bilang komoditas tambang salah sumber cari alternatifalternatif dapat negara kena pajak ekspor hasil hilir bidik kena pajak ekspor produk nickel pig iron npi produk hasil olah bijih nikel laterit kadar rendah industri npi besi mentah pig iron fungsi bahan baku utama industri stainless steel baja tahan karat alternatif feronikel murah  npi npi produk nikel hitung hitung ya hitung formulasi kena pajak npinya  bahlil
================================================================================

In [35]:
#16. Menyimpan Data Hasil Preprocessing
output_columns = [text_column, "clean_text", "processed_text"]

data[output_columns].to_csv("dataset_processed.csv", index=False)

print("Data berhasil disimpan.")

Data berhasil disimpan.

In [36]:
# Membuat kolom hasil cleaning
data["clean_text"] = data[text_column].apply(clean_text)

# Cek hasil
data[[text_column, "clean_text"]].head(10)

,content_article,clean_text
0,reporter noverius laoli editor noverius laoli ...,reporter noverius laoli editor noverius laoli ...
1,reporter kompascom editor noverius laoli konta...,reporter kompascom editor noverius laoli konta...
2,reporter noverius laoli editor noverius laoli ...,reporter noverius laoli editor noverius laoli ...
3,format nontextgagal ekstrak,format nontextgagal ekstrak
4,reporter sabrina rhamadanty editor ignatia mar...,reporter sabrina rhamadanty editor ignatia mar...
5,reporter kompascom editor noverius laoli konta...,reporter kompascom editor noverius laoli konta...
6,kontancoid yuk lihat harga emas hari ini di pe...,kontancoid yuk lihat harga emas hari ini di pe...
7,reporter dimas andi editor tri sulistiowati ko...,reporter dimas andi editor tri sulistiowati ko...
8,kontancoid yuk lihat harga emas antam logam mu...,kontancoid yuk lihat harga emas antam logam mu...
9,sumber reuters editor khomarul hidayat kontanc...,sumber reuters editor khomarul hidayat kontanc...